import { NamespaceStore } from "../plugins/houdini-svelte/stores/Namespace";
import type { Cache as InternalCache } from "./cache/cache";
import type { CacheTypeDef } from "./generated";
import { Cache } from "./public";
export * from "./client";
export * from "./lib";
export function graphql(str: "query Namespace {\n\tnamespaces {\n\t\tname\n\t}\n}\n"): NamespaceStore;
export declare function graphql<_Payload, _Result = _Payload>(str: TemplateStringsArray): _Result;
export declare const cache: Cache<CacheTypeDef>;
export declare function getCache(): InternalCache;