package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"koda/services/orchestrator/graph/model"
)

// CreateNamespace is the resolver for the createNamespace field.
func (r *mutationResolver) CreateNamespace(ctx context.Context, options model.NamespaceOptions) (*model.Namespace, error) {
	// TODO: Implement
	return nil, nil
}

// DeleteNamespace is the resolver for the deleteNamespace field.
func (r *mutationResolver) DeleteNamespace(ctx context.Context, id string) (string, error) {
	// TODO: Implement
	return "deleted", nil
}

// Namespaces is the resolver for the namespaces field.
func (r *queryResolver) Namespaces(ctx context.Context) ([]model.Namespace, error) {
	// get namespaces from kubernetes
	namespaces, err := r.Kubernetes.Namespaces(ctx)
	if err != nil {
		return nil, err
	}

	namespacesModel := make([]model.Namespace, len(namespaces))
	for i, namespace := range namespaces {
		namespacesModel[i] = model.Namespace{
			Name: namespace.Name,
		}
	}

	return namespacesModel, nil
}

// Namespace is the resolver for the namespace field.
func (r *queryResolver) Namespace(ctx context.Context, id string) (*model.Namespace, error) {
	// TODO: Implement
	return nil, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
